### ISSUE TITLE
Applications from **secondary** strata dont display in tray.

### ISSUE THREAD

**Issue by SolitudeSF** [bedrocklinux/bedrocklinux-userland#92] opened 2018-12-20 13:31 UTC
Bedrock hijacked onto install of void. I installed steam and qbittorrent from arch. Neither of those appear in tray when launched.

**Comment by paradigm** [comment] 2018-12-20 13:55
What program/package from which distro is providing your tray?

**Comment by SolitudeSF** [comment] 2018-12-20 13:56
polybar from void

**Comment by paradigm** [comment] 2018-12-20 13:58
Off the top of my head I don't know how trays actually work.  When I get the chance I'll take a look and see if I can reproduce it, then dig into it.

**Comment by SolitudeSF** [comment] 2018-12-20 14:02
using polybar from arch yield same result, btw

**Comment by paradigm** [comment] 2018-12-20 14:05
Is anything creating tray entries?  If your whole stack is Void do tray entries show up?  Or is it just Arch's programs that aren't showing up?

If it's *just* Arch's, and the issue arises irrelevant of who provides the tray, than it may be tied to some other subsystem.  Maybe some service the init starts, like dbus.

**Comment by SolitudeSF** [comment] 2018-12-20 14:08
only programs from arch arent showing.
i have dbus service enabled in runit. but i have 0 clue on how dbus operates, i just know that i need the service enabled for steam to work.

**Comment by SolitudeSF** [comment] 2018-12-20 14:10
just disabled it. steam still works. but there are bunch of instances of dbus-daemon spawned by firefox and other programs so idk

**Comment by paradigm** [comment] 2018-12-20 14:15
While I haven't done so yet, I expect I have enough information to replicate the issue.  Once I get the chance I'll mix and match any remaining variables until I've found the pattern, then dive into the relevant subsystems to see where they're failing to communicate.

**Comment by paradigm** [comment] 2018-12-27 19:00
I couldn't reproduce it.

I hijacked Void and installed xorg, openbox, and polybar.  At the end of the install were instructions to copy provided example configuration into place for use and launch with the example configuration, which I did.  I threw

	#!/bin/sh
	polybar &
	openbox

into `~/.xinitrc` and `startx`'d.  I then fetched arch and installed `qbittorrent` from it and ran it.  After dismissing a prompt the icon showed up in the tray as one would typically expect.

I tried variations such as hijacking Ubuntu and fetching Void, rebooting with Void's init, and using Ubuntu's qbittorrent.  All seem to work.

**Comment by SolitudeSF** [comment] 2018-12-27 19:58
Weird, on my reinstalled system, i tried installing qbittorent from arch and it displays tray icon. But steam doesn't. And i can blame anything on steam, tbh.

**Comment by paradigm** [comment] 2018-12-27 21:17
I just tried Steam.  An icon shows up in the tray that I can right click and get the expected Steam content.  However, the icon is a missing-icon indicator.  That might be due to [this issue](https://bedrocklinux.org/0.7/known-issues.html#missing-application-icons) maybe?  Irrelevant of why, I think that'd be a separate issue.

If you don't mind, I'm inclined to close this issue, as cross-stratum icons do seem to be showing up in the tray for both of us.  If you are able to reproduce it with anything else, feel free to re-open it with the additional information.

**Closed by paradigm** 2018-12-27 21:17 UTC
