### ISSUE TITLE
"./bedrocklinux-installer make all" fails on 1.0beta1 branch

### ISSUE THREAD

**Issue by mczero80** [bedrocklinux/bedrocklinux-userland#44] opened 2015-12-01 11:00 UTC
I'm doing a fresh new install of bedrock linux.

Everything worked so far, `./bedrocklinux-installer source all` gave no errors. 

I have followed the recommended way of installing Bedrock Linux, as described on http://bedrocklinux.org/1.0beta1/install.html .

But then `./bedrocklinux-installer make all` fails with a missing musl-gcc executable.

I use Xubuntu 14.04 as a Host-Install Environment.

Logfile is attached.

[log.txt](https://github.com/bedrocklinux/bedrocklinux-userland/files/48403/log.txt)

**Comment by paradigm** [comment] 2016-01-17 11:43
I've not been able to reproduce that issue.  However, the build system had a
major rework for the 1.0beta2 release that just went out.  Can you see if the
issue persists for you in this new release?

If you don't want to dig through all of the instructions, you can probably just
do the following to test the new build system:

- Install gcc.  Note that there's a bug in gcc 4.8.2 and 4.9.0 (and 4.9.1?)
  which bites us; see if you can get either an older release such as 4.7.X or,
  more likely, a newer release such as 4.9.2 or higher.
- Install make, git, autoconf, automake, libtool, gettext, and fakeroot

Run:

    git clone --branch 1.0beta2 https://github.com/bedrocklinux/bedrocklinux-userland.git

to get the 1.0beta2 release code, then


    cd bedrocklinux-userland
    make

If all goes well, you'll have a tarball in your current working directory.  If
not, then the issue persists for you and we'll need to narrow down what's going
on.

**Comment by paradigm** [comment] 2018-12-27 15:51
Given that two major releases have come and gone since this which include major reworkings of the build system, I'm closing this.  If the issue is found to continue with the current system, do fee free to re-open.

**Closed by paradigm** 2018-12-27 15:51 UTC

**Comment by mczero80** [comment] 2018-12-27 17:45
Yeah, I am sorry for not replying and giving feedback. I guess I had much real life work to do. 
Sounds good, I haven't tried the new release yet.

**Comment by paradigm** [comment] 2018-12-27 19:45
No worries, I absolutely understand being busy.  Having that issue linger wasn't a problem.  Should you get around to it, do let me know, but no pressure to make this any what of a priority.
