### ISSUE TITLE
0.7.29beta1 setcap is not static linked

### ISSUE THREAD

**Issue by naY9yjoS6ZqhOd35sIFH** [bedrocklinux/bedrocklinux-userland#295] opened 2023-08-04 23:38 UTC
line 2307: /bedrock/libexec/setcap: No such file or directory
setcap elf seems dynamic
version 0.7.29beta1 
platform x86_64

**Comment by paradigm** [comment] 2023-08-05 02:36
Good catch.  I can confirm the issue.  I double checked the other binaries and it didn't seem to hit them, just `setcap`.

There were two problems:

1. I updated the `setcap` version, and apparently it's build system has since introduced a bug where it no longer respects a request to statically link its binaries.[I found a work around.](https://github.com/bedrocklinux/bedrocklinux-userland/commit/72f235d6f383b9a541a11dd826319aa56cb93139)

2. While Bedrock's build system does explicitly check for this concern, apparently the check isn't sufficiently robust and this slipped through.  [I've improved the check accordingly.](https://github.com/bedrocklinux/bedrocklinux-userland/commit/cb13137fcb92183acb0d76a93d56fd7ffa4aaeb1)

0.7beta2 with these changes building now. I'll push the update once it's ready.

**Comment by paradigm** [comment] 2023-08-05 03:08
Thanks for helping beta and being so quick to report the issue.

I've pushed beta2 with the fix, and I am closing the ticket.  If you think I missed or misunderstood something, do feel free to open it accordingly.

**Closed by paradigm** 2023-08-05 03:08 UTC
