### ISSUE TITLE
Programs using dbus wont launch

### ISSUE THREAD

**Issue by SolitudeSF** [bedrocklinux/bedrocklinux-userland#89] opened 2018-11-17 17:58 UTC
Some programs that rely on the dbus for their core functionality refuse to launch, like `dunst` or `kbdd`. I have dbus service enabled in base system (void), even tho it wasn't ever needed for these programs, since they launch their own userlevel instance.

launching program with `dbus-launch` gives this error:
```
 ▲ ~  dbus-launch dunst                                                                                                
D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; Failed to open "/etc/machine-id": No such file or directory)
```

and the entire thing fixes itself after running `sudo dbus-uuidgen --ensure`, but i don't know if previous behavior is correct.

**Comment by Mouvedia** [comment] 2018-11-17 21:29
Is this a dupe of #62?

**Comment by paradigm** [comment] 2018-11-17 22:24
@Mouvedia

Without the error message, I'd have thought so as well.  However, the error message and fix seems to be about the fact that `machine-id` is missing, rather than sharing dbus activation config files that #62 was about (but didn't explain well).

@SolitudeSF

I can't trivially reproduce this, as it all works for me on my test machines.  In fact, I use dunst regularly.  Let's get more information about your setup that I can use to try and reproduce the issue:

- `brl deref hijacked`
- `brl deref init`
- `brl which -p 1`
- `brl which -p $(pidof dbus-daemon)`
- `brl which dunst`
- `brl which dbus-launch`
- `ls -l /var/lib/dbus/machine-id`
- `ls -l /etc/machine-id`

With that I'll see if I can spin up a VM and retrace your steps.

I know a fresh install of Void Linux does not have `dbus` or `machine-id`, but `xbps-install`'ing `dbus` seems to create a `machine-id`.  Bedrock shouldn't remove it.  However, Bedrock *does* touch it, as it tries to standardize the location via symlinks (as some distros use `/var/lib/dbus/machine-id` and some use `/etc/machine-id`, and for them to coordinate they need to effectively see both paths).  If there's a bug in Bedrock's code there it's not impossible that makes it disappear.

**Comment by SolitudeSF** [comment] 2018-11-18 08:00
Every `deref` and `which` points to void.
After reboot
```
> ls -l /var/lib/dbus/machine-id                                                                                 
lrwxrwxrwx 1 root root 15 Nov 18 09:23 /var/lib/dbus/machine-id -> /etc/machine-id

> ls -l /etc/machine-id                                                                                          
/usr/sbin/ls: cannot access '/etc/machine-id': No such file or directory
```
And after running `sudo dbus-uuidgen --ensure`
```
> ls -l /var/lib/dbus/machine-id                                                                                 
-rw-r--r-- 1 root root 33 Nov 18 09:58 /var/lib/dbus/machine-id
```

**Comment by SolitudeSF** [comment] 2018-11-18 12:15
yes, i hijacked bedrock onto my daily driver install of void, so it had dbus already.

**Comment by SolitudeSF** [comment] 2018-11-18 21:38
yep, dbus and apps now working correctly. thanks!

**Closed** 2018-11-18 21:39 UTC

**Comment by SolitudeSF** [comment] 2018-11-19 19:52
on a freshly installed system i still needed to do `dbus-uuidgen --ensure` once

**Comment by SolitudeSF** [comment] 2018-11-19 22:35
yeah, i worded that wrong, not exactly fresh, but with dbus and connman installed. so dbus was present and running as a service when i hijacked. maybe that was onetime error with dunst or whatever. dont really want to reinstall again just to check. and dont want to put all the blame on the bedrock since my system lately behaves incorrectly in many ways even without bedrock.

**Comment by paradigm** [comment] 2018-11-20 00:42
I wasn't able to reproduce that, either.  I installed a fresh Void Linux, installed dbus, hijacked it (and rebooted), then found both `/etc/machine-id` and `/var/lib/dbus/machine-id` setup as Bedrock intends them to be.  Various dbus tests worked as expected.

Don't feel obligated to retrace your steps to reproduce the issue if it's overly time consuming or tedious.  You've already helped find a number of things in the beta and have my thanks.  If it's a fluke, c'est la vie, and if not someone else will find it in the future and I'll have a better eye for where to look when debugging it.
