### ISSUE TITLE
emacs installed in non-root (global?) stratum cannot see things not in home directory

### ISSUE THREAD

**Issue by emacsomancer** [bedrocklinux/bedrocklinux-userland#80] opened 2017-09-06 22:31 UTC
For some reason, `emacs` installed in a non-root (or maybe non-global?) stratum, when run, claims anything not in the home directory is missing. E.g. it cannot see `/usr/local/share/emacs/site-lisp`. `emacs` installed in the root stratum has no such difficulties.

**Comment by paradigm** [comment] 2017-09-07 00:18
What do you mean by "cannot see"?  Can you give me more explicit steps describing what you're doing to reproduce the issue?

I'll take a guess as to what's wrong.  A bit of review on how Bedrock Linux works, as I think it will likely be pertinent:

Bedrock Linux breaks up files into two categories, [local and global](https://bedrocklinux.org/1.0beta2/concepts.html#local-vs-global):

> If two pieces of software both require different file contents at a given path, for both to work two instances of the given file must exist such that each piece of software will see the file it expects at the given path. Bedrock Linux refers to files with this requirement as local files.

> In contrast to local files are global files: files which must be the same when different pieces of software from different expected environments attempt to utilize it.

> For example, /etc/apt/sources.list is a local file. Debian's apt-get and Ubuntu's apt-get should see different file contents when reading /etc/apt/sources.list, as both will have different mirrors and configuration for their package managers. Thus, if a given Bedrock Linux install has both Debian's and Ubuntu's apt-get, it will also have two copies of /etc/apt/sources.list.

> /etc/passwd is a global file. When software from different distributions attempt to match a UID to a username, the pairing should be consistent.

If a file is a local one, Bedrock Linux is usually pretty smart about automatically determining which one to use.  However, there's limits to what it can do automatically.  Sometimes it will guess wrong, in which case you'll need to tell it more explicitly what file you're referring to.  Going along with the above example, if you do `vim /etc/apt/sources.list`, do you want to edit Debian's `/etc/apt/sources.list` or Ubuntu's?  Even if there was a reasonably bright human intelligence intercepting that command, there's no obvious way to figure out which is desired in that specific instance.

By default, `/usr/local/share/emacs/site-lisp` is a local path.  Thus, you have multiple possible files at this path - up to one per stratum.  Bedrock Linux does this because different things which populate `/usr/local/` could be distro-specific and conflict between distros.  For example, Arch's AUR often puts binaries in there which are linked against Arch libraries.

By default, if a process looks for something at a local path, it'll check the instance corresponding to its own stratum.  Debian's `apt` will look at Debian's `/etc/apt/sources.list` and Ubuntu's `apt` will look at Ubuntu's `/etc/apt/sources.list`.  This is a fairly good default that works the vast majority of the time.

My guess is you've got `emacs` from one stratum and have populated the `/usr/local/share/emacs/site-lisp` corresponding to another stratum.  I can't be certain of that from the description you've provided - more information is needed - but that's my current guess based on what you've said so far.

If that's the case, you've got a few options:

- Populate the `/usr/local/share/emacs/site-lisp` corresponding to the same stratum that provides emacs.  I don't know emacs well enough to have a guess for how you're populating it.  If this isn't hard to do, it's the easiest solution.
- Use a global directory instead of `/usr/local/share/emacs/site-lisp`.  For example, as you've already found `/home`.  Other global directories include `/tmp` and `/mnt`.  Again, I don't know emacs well enough to know if there's something important about `/usr/local/share/emacs/site-lisp` which makes it prefered.
- Use an [explicit path](https://bedrocklinux.org/1.0beta2/concepts.html#explicit) where you tell Emacs which stratum's instance of `/usr/local/share/emacs/` to look at, e.g. `emacs /bedrock/strata/gentoo/usr/local/share/emacs/site-lisp/example.el`.  Again, I don't know Emacs well enough to know if there's a reason this is a bad idea.
- Make `/usr/local/share/emacs/site-lisp` global.  This way there will only be one such set of files system-wide and no confusion about where to find them.  This will almost certainly make Emacs happy.  The downside is if you've got multiple strata who each think they "own" those files (e.g. different package managers controlling them), it'll make those strata/package-managers fight.  To make it global, add it to a `shared =` line in `/bedrock/etc/frameworks.d/default` and `brs update` the relevant strata (possibly all of them).  Note doing this may make it appear the directory has been emptied, and thus you may have to (re)populate `/usr/local/share/emacs/site-lisp` after doing so.  If that's populated by some package manager, make sure to uninstall the relevant package first, *then* make the path global, *then* re-install it.  Otherwise it'll look like the files were deleted.

Let me know more specifically what you're doing to reproduce the issue if the above description doesn't seem applicable.

**Comment by emacsomancer** [comment] 2017-09-07 00:51
Hmm... I had already tried after installing the relevant `site-lisp` packages from the (non-root) distro that I was trying to run emacs from, and it still claimed it couldn't find the files.  

The problem is that it isn't just `/usr/local/share/emacs/site-lisp`, but there seem to be quite a number of locations it's looking for.  So it may be irritating to try to deal with all of these. 

I'll play with it some more (thanks for the many helpful pointers - I'll refer back to those) at some point. (Probably I'll try to fix the issues internal to Void pertaining to emacs first; I had just defaulted to the path of less resistance trying to use Arch's emacs instead.)

**Comment by paradigm** [comment] 2017-09-07 01:15
> Hmm... I had already tried after installing the relevant site-lisp packages from the (non-root) distro that I was trying to run emacs from, and it still claimed it couldn't find the files.

Then something weird is going on and my above guess is wrong.  My guess was that you were getting emacs from one stratum and the site-lisp items from another.  If both emacs and the site-lisp packages are all installed in the same stratum, emacs should be able to find them just fine without any extra work.

Can you give me a more specific example, such as what packages to install in which distro to install to reproduce the issue, and what command to run to reproduce the error message?  For example, "install emacs and emacs-calfw in Arch then run emacs --calfw" or something along those lines.

> The larger issue is that it isn't just /usr/local/share/emacs/site-lisp, but there seem to be quite a number of locations it's looking for. So it may be irritating to try to deal with all of these.

If there's some scenario where we have to hunt down and specially configure bedrock for a *lot* of paths, something else is wrong; that shouldn't be an acceptable solution.

> I'll play with it some more (thanks for the many helpful pointers - I'll refer back to those) at some point.

I'd actually prefer you didn't, as I think that may make debugging whatever the underlying issue is more difficult.  The items I laid out were all for a guess that, per your first line, isn't the case.

**Comment by emacsomancer** [comment] 2017-09-07 03:28
I was running mu4e, but one would need to reference the relevant install location in the emacs config file (and surely the other 'missing' locations are also things referenced in my particular config).

**Comment by paradigm** [comment] 2018-12-27 16:56
Poki's architecture is significantly different in this regard.  I'm closing under the assumption it's no longer valid.  If you can reproduce this in Poki feel free to re-open it.

**Closed by paradigm** 2018-12-27 16:56 UTC
